name = "telegram-e2e-runner-bot"
main = "src/worker.mjs"
compatibility_date = "2026-03-06"

kv_namespaces = [
  { binding = "BOT_STATE_KV", id = "dfd4b24b750a4ad19497a9531f44422c", preview_id = "1624c0302b314c939ccbcf51c49f5efa" }
]

[vars]
GITHUB_WORKFLOW_FILE = "telegram-web-e2e.yml"
GITHUB_REF = "main"
DEFAULT_SUITE = "autorun"
GITHUB_OWNER = "pushpull-code"
GITHUB_REPO = "telegram-web-e2e"
